# Generated by Django 3.2 on 2023-07-29 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.UUIDField(default=uuid.UUID('6b9c7173-90f2-412f-ae7b-20b89bbdede7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workspace_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workflow.workspace'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='workflow_trigger_id',
            field=models.UUIDField(default=uuid.UUID('d77c556d-4400-4047-a826-29501e28a766'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_id',
            field=models.UUIDField(default=uuid.UUID('08aa7c3e-6b7c-45ce-9fac-ab81a8fd8f3a'), primary_key=True, serialize=False),
        ),
    ]
