# Generated by Django 3.2 on 2023-07-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20230729_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.UUIDField(default=uuid.UUID('99e331e5-fd4f-46ab-ad34-3f7e78a220bd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_triggers', to='workflow.workflow'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='workflow_trigger_id',
            field=models.UUIDField(default=uuid.UUID('48a19e2d-b2ae-4071-ad91-cf10c4f03d2b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_id',
            field=models.UUIDField(default=uuid.UUID('ac2c6877-12fd-45ce-950d-eba7572067d9'), primary_key=True, serialize=False),
        ),
    ]
