# Generated by Django 3.2 on 2023-08-06 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_workflow_workflow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.UUIDField(default=uuid.UUID('bb8a5e2d-ee46-4727-9eaa-1a3852224238'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='workflow_trigger_id',
            field=models.UUIDField(default=uuid.UUID('e1e3eb6a-5494-4a01-b72c-0a7005d3bda2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_id',
            field=models.UUIDField(default=uuid.UUID('7665d049-f17f-4fb4-89b6-ce1b83c96ecd'), primary_key=True, serialize=False),
        ),
    ]
