# Generated by Django 3.2 on 2023-08-07 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20230807_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_id',
            field=models.UUIDField(default=uuid.UUID('0ffbbc62-0882-4906-bb10-af78ffa99b3c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='workflow_trigger_id',
            field=models.UUIDField(default=uuid.UUID('e1922c86-da13-403a-8035-3beac351bc04'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_id',
            field=models.UUIDField(default=uuid.UUID('6feafb00-f7b6-4cb4-9160-bd68142fada0'), primary_key=True, serialize=False),
        ),
    ]
